package com.nirwansyah.springboot.entities;
// Generated Apr 3, 2017 10:32:18 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nasabah generated by hbm2java
 */
@Entity
@Table(name="nasabah"
    ,catalog="crud_banking"
)
public class Nasabah  implements java.io.Serializable {


     private Integer idnasabah;
     private String alamat;
     private String nama;
     private String notelp;

    public Nasabah() {
    }

    public Nasabah(String alamat, String nama, String notelp) {
       this.alamat = alamat;
       this.nama = nama;
       this.notelp = notelp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idnasabah", unique=true, nullable=false)
    public Integer getIdnasabah() {
        return this.idnasabah;
    }
    
    public void setIdnasabah(Integer idnasabah) {
        this.idnasabah = idnasabah;
    }

    
    @Column(name="alamat", nullable=false)
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    
    @Column(name="nama", nullable=false)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

    
    @Column(name="notelp", nullable=false)
    public String getNotelp() {
        return this.notelp;
    }
    
    public void setNotelp(String notelp) {
        this.notelp = notelp;
    }




}


